### PR TITLE
feat: resolve display name from MemberExpression

### PR DESCRIPTION
**Pull request by jquense**
Add support for resolving names from member expressions and assigments, as well as not crashing when `getNameOrValue` doesn't have the correct node (which seems to have been the original intent)

### CODE REVIEW

**Comment by jquense** [comment]
ugh sorry for all the formatting, prettier decided to activate itself, one sec

**Comment by ZauberNerd** [comment]
@jquense thank you for your contribution!
I'm currently setting up automated testing and automated releases - would you mind waiting on #5 and rebasing after that is merged?

**Comment by ZauberNerd** [comment]
Thanks! ♥️

**Comment by jquense** [comment]
awesome thanks!

**Pull request merged**
